name: Test Action

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering from the GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 23f2002592@ds.study.iitm.ac.in
        run: echo "Hello, world!"

